# Generated by Django 4.2.5 on 2024-03-22 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(default=160, validators=[django.core.validators.MinValueValidator(61.0), django.core.validators.MaxValueValidator(250.0)]),
        ),
    ]
