# Generated by Django 5.0.3 on 2024-04-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('POSE', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('VIEW', models.CharField(max_length=255)),
                ('ORIENTATION', models.CharField(max_length=255)),
                ('KNEE', models.IntegerField(default=1)),
                ('HIP', models.IntegerField(default=1)),
                ('TORSO', models.IntegerField(default=1)),
                ('SHOULDER', models.IntegerField(default=1)),
                ('ELBOW', models.IntegerField(default=1)),
                ('ANKLE', models.IntegerField(default=1)),
                ('NECK', models.IntegerField(default=1)),
                ('WRIST', models.IntegerField(default=1)),
                ('LEFT_ANKLE_AR', models.TextField(null=True)),
                ('RIGHT_ANKLE_AR', models.TextField(null=True)),
                ('LEFT_KNEE_AR', models.TextField(null=True)),
                ('RIGHT_KNEE_AR', models.TextField(null=True)),
                ('HIP_AR', models.TextField(null=True)),
                ('LEFT_TORSO_AR', models.TextField(null=True)),
                ('RIGHT_TORSO_AR', models.TextField(null=True)),
                ('LEFT_SHOULDER_AR', models.TextField(null=True)),
                ('RIGHT_SHOULDER_AR', models.TextField(null=True)),
                ('LEFT_ELBOW_AR', models.TextField(null=True)),
                ('RIGHT_ELBOW_AR', models.TextField(null=True)),
                ('LEFT_WRIST_AR', models.TextField(null=True)),
                ('RIGHT_WRIST_AR', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yoga',
            fields=[
                ('POSE', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('VIEW', models.CharField(max_length=255)),
                ('ORIENTATION', models.CharField(max_length=255)),
                ('KNEE', models.IntegerField(default=1)),
                ('HIP', models.IntegerField(default=1)),
                ('TORSO', models.IntegerField(default=1)),
                ('SHOULDER', models.IntegerField(default=1)),
                ('ELBOW', models.IntegerField(default=1)),
                ('ANKLE', models.IntegerField(default=1)),
                ('NECK', models.IntegerField(default=1)),
                ('WRIST', models.IntegerField(default=1)),
                ('LEFT_ANKLE_AR', models.TextField(null=True)),
                ('RIGHT_ANKLE_AR', models.TextField(null=True)),
                ('LEFT_KNEE_AR', models.TextField(null=True)),
                ('RIGHT_KNEE_AR', models.TextField(null=True)),
                ('HIP_AR', models.TextField(null=True)),
                ('LEFT_TORSO_AR', models.TextField(null=True)),
                ('RIGHT_TORSO_AR', models.TextField(null=True)),
                ('LEFT_SHOULDER_AR', models.TextField(null=True)),
                ('RIGHT_SHOULDER_AR', models.TextField(null=True)),
                ('LEFT_ELBOW_AR', models.TextField(null=True)),
                ('RIGHT_ELBOW_AR', models.TextField(null=True)),
                ('LEFT_WRIST_AR', models.TextField(null=True)),
                ('RIGHT_WRIST_AR', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(null=True)),
                ('Steps', models.TextField(null=True)),
                ('Advantage', models.TextField(null=True)),
                ('Precaution', models.TextField(null=True)),
                ('GIF', models.TextField(null=True)),
                ('POSE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_profile', to='core.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='YogaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(null=True)),
                ('Steps', models.TextField(null=True)),
                ('Advantage', models.TextField(null=True)),
                ('Precaution', models.TextField(null=True)),
                ('GIF', models.TextField(null=True)),
                ('POSE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yoga_profile', to='core.yoga')),
            ],
        ),
    ]
