# Generated by Django 5.0.3 on 2024-03-30 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseprofile',
            name='POSE',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_profile', to='core.exercise'),
        ),
        migrations.AlterField(
            model_name='yogaprofile',
            name='POSE',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yoga_profile', to='core.yoga'),
        ),
    ]
