# Generated by Django 4.2.7 on 2024-03-31 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_exerciseprofile_pose_alter_yogaprofile_pose'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaGif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GIF', models.TextField(null=True)),
                ('POSE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yoga_gif', to='core.yoga')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseGif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GIF', models.TextField(null=True)),
                ('POSE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_gif', to='core.exercise')),
            ],
        ),
    ]
